set history=100000

set number

set autoindent
"set smartindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

set hlsearch

set colorcolumn=81

set background=dark

" So you can edit Makefile
autocmd FileType make setlocal noexpandtab


